name: Node.js Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn build-storybook
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
        run: |
          aws s3 cp --recursive --region ap-northeast-2 \
            storybook-static s3://dndn-storybook

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: yarn install --frozen-lockfile
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

          #  build:
          #    runs-on: ubuntu-latest
          #
          #    strategy:
          #      matrix:
          #        node-version: [12.x]
          #
          #    steps:
          #      - uses: actions/checkout@v2
          #      - name: 노드버전 ${{ matrix.node-version }}
          #        uses: actions/setup-node@v1
          #        with:
          #          node-version: ${{ matrix.node-version }}
          #      - run: npm config set registry http://registry.npmjs.org
          #      - run: npm install -g yarn@1.22.4
          #      - run: npm install -g serverless@1.76.1
          #      - run: npm install -g aws-cloudfront-invalidate
          #      - run: yarn
          #      - run: yarn build:production
          #      - run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}
          #      - run: yarn deploy:production
          #      - run: aws-cloudfront-invalidate E3P9YJE6TKFB4 /*
